name: Build and Upload Artifacts

on: [push, pull_request]

env:
  GO_VERSION: "1.21"

jobs:
  prepare:
    runs-on: macos-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
  build-macos-arm64:
    needs: prepare
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          env GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags="-s -w" -o macos-arm64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: macos-arm64
  build-macos-amd64:
    needs: prepare
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          env GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o macos-amd64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd64
          path: macos-amd64
  build-windows-arm64:
    needs: prepare
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          env GOOS=windows GOARCH=arm64 go build -trimpath -ldflags="-s -w" -o windows-arm64.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-arm64.exe
          path: windows-arm64.exe
  build-windows-amd64:
    needs: prepare
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          env GOOS=windows GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o windows-amd64.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64.exe
          path: windows-amd64.exe
  build-linux-arm64:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          env GOOS=linux GOARCH=arm64 go build -trimpath -ldflags="-s -w" -o ubuntu-arm64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-arm64
          path: ubuntu-arm64
  build-linux-amd64:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          env GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o ubuntu-amd64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-amd64
          path: ubuntu-amd64
